In this notebook we`re going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we`re going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function (a way to speed up your regular Python functions
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try myself

Introduction to Tensors

In [172]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.1


In [173]:
# Create tensors with tf.constant()
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [174]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions
scalar.ndim

0

In [175]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [176]:
# Check the dimension of our vector
vector.ndim

1

In [177]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 10], [20, 20]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 10],
       [20, 20]], dtype=int32)>

In [178]:
# Check the dimension of matrix
matrix.ndim

2

In [179]:
# Create another matrix
another_matrix = tf.constant([[10, 10], [20, 20], [30, 30]], dtype = tf.float16) # specify the data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 10.],
       [20., 20.],
       [30., 30.]], dtype=float16)>

In [180]:
# The number of dimensions of another_matrix
another_matrix.ndim

2

In [181]:
# Let`s create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [182]:
tensor.ndim

3

What we`ve created so far:
* Scalar: a single number
* Vector: a number with direction (e.g wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: a n-dimensional array of numbers (when n can be any  number)

### Creating tensors with tf.Variable

In [183]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [184]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 10])
unchangeable_tensor = tf.constant([5, 5])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([5, 5], dtype=int32)>)

In [185]:
# Let`s try change one of the elements in our changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let`s try change our unchangeable tensor
unchangeable_tensor[0].assign(888)

# Creating random tensors

Random tensors are tensors of some arbitrary size which contains random numbers

In [ ]:
# Create two random but the same tensors

random_1 = tf.random.Generator.from_seed(5) # set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(5)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_1 == random_2

### Shuffle the order of elements in a tensor

In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn`t effect learning)
not_shuffled = tf.constant([[10, 11],
                           [12, 13],
                           [14, 15]])
not_shuffled.ndim

In [ ]:
not_shuffled

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled, seed=5)

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.set_seed(5)
tf.random.shuffle(not_shuffled)

In [ ]:
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled)

In [ ]:
var = tf.constant([[1, 2, 3],
                   [4, 4 ,22],
                   [1, 22, 33],
                   [13, 1231, 11]])
tf.random.shuffle(var), tf.random.shuffle(var), tf.random.shuffle(var, seed=5), tf.random.shuffle(var, seed=5)

In [ ]:
var1 = tf.random.normal(shape=(3, 1, 4), seed=4)
var1
tf.random.set_seed(seed=12)
var1, tf.random.shuffle(var1), tf.random.shuffle(var1), tf.random.shuffle(var1, seed=12), tf.random.shuffle(var1, seed=12)

In [ ]:
# Create a tensor of all ones
tf.ones(shape = (10,10))


In [ ]:
# Crete a tensor of all zeros
tf.zeros([10, 10])

### Turn NumPy arrays into tensors
The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU(much faster  for numerical computing)

In [187]:
import numpy as np

numpy_A = np.arange(1, 15, dtype = np.int32) # Create a NumPy array between 1 and 15
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2, 1, 7))
A

### Getting information from tensors
When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis of dimension
* Size

In [ ]:
# Create a rank 4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

In [ ]:
rank_4_tensor[0]

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions(rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis", rank_4_tensor.shape[-1])
print("The total elements in our tensor", tf.size(rank_4_tensor).numpy())
print("The total elements in our tensor", tf.size(rank_4_tensor))

### Indexing tensors

Tensors can be indexed just like Python lists


In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1]

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10, 7],
                           [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

In [ ]:
# Get the last item of each raw of our rank 22 tensor
rank_2_tensor[:,:-1]

In [ ]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

In [ ]:
# Alternative to rf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expand the final axis

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

In [ ]:
rank_2_tensor

### Matrix multiplication

In machine learning, matrix multiplications is one of the most common tensor operations

In [ ]:
# Matrix multiplication in tensorflow

tensor = tf.random.normal([2,2])
tensor, tf.matmul(tensor, tensor), tensor * tensor

In [ ]:
# Matrix multiplication with Python operator @

tensor@tensor

In [ ]:
# Find the variance of our tensor
tf.reduce_variance(tensor) # won`t work...

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(tensor), tf.math.reduce_variance(tf.cast(tensor, dtype=tf.float32))

In [ ]:
# Find the standard deviation
tf.reduce_std(tensor) # won`t work

In [ ]:
tf.math.reduce_std(tensor)

In [ ]:
tf.math.reduce_std(tf.cast(tensor, dtype=tf.float32))

 ### Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

In [ ]:
# Find the positional maximum
tf.argmax(F)

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

In [ ]:
# Find the max value of F
tf.reduce_max(F)

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

In [ ]:
# Find the positional minimum
tf.argmin(F)

In [ ]:
# Index on our smallest value position
F[tf.argmin(F)]

In [ ]:
tf.reduce_min(F)

### Squeezing a tensor (moving all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

In [ ]:
G.shape

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

### One hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] # Could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list)

In [ ]:
tf.one_hot(some_list, depth=4)

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value='yo I live deep learning', off_value='I also like to draw')

### Squaring, log, square root

In [ ]:
H = tf.range(1, 10)
H

In [ ]:
# Square it
tf.square(H)

In [ ]:
# Square root
tf.math.sqrt(H) # will error, method requires non-int type

In [ ]:
tf.math.sqrt(tf.cast(H, dtype=tf.float32))

In [ ]:
# Find the log
tf.math.log(H) # will error, method requires non-int type

In [ ]:
tf.math.log(tf.cast(H, dtype=tf.float32))

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy Arrays.

In [188]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 8., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  8., 10.])>

In [189]:
# Convert our tensor back to a Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  8., 10.]), numpy.ndarray)

In [190]:
# Convert tensor J to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  8., 10.]), numpy.ndarray)

In [193]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 10., 7.]))
tensor_J = tf.constant([3., 10., 7.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [196]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [197]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### TensorFlow Fundamentals Exercises


In [198]:
# 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

vector = tf.constant([1, 222, 3, 4])
scalar = tf.constant(10)
matrix = tf.constant(tf.random.uniform(shape=[50], minval=10, maxval=20), shape=(5, 10))
tensor = tf.constant(tf.random.normal(shape=[50]), shape=(5, 5, 2))
vector, scalar, matrix, tensor

(<tf.Tensor: shape=(4,), dtype=int32, numpy=array([  1, 222,   3,   4], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(5, 10), dtype=float32, numpy=
 array([[16.878912 , 14.844789 , 19.309944 , 12.52187  , 17.311539 ,
         18.925682 , 19.467484 , 17.493341 , 13.492563 , 15.471826 ],
        [12.616039 , 16.973433 , 11.196259 , 15.348434 , 17.148968 ,
         18.750177 , 13.3967495, 11.737762 , 14.418521 , 19.00826  ],
        [11.380386 , 11.221798 , 15.754491 , 19.417181 , 19.186584 ,
         15.970848 , 16.109482 , 18.208626 , 18.326979 , 18.915848 ],
        [10.137722 , 14.980746 , 15.750366 , 16.856194 , 17.597279 ,
         19.08944  , 14.090022 , 18.765154 , 15.389003 , 14.27331  ],
        [14.01173  , 16.662325 , 11.634807 , 11.822024 , 19.704018 ,
         10.613974 , 15.303474 , 19.869995 , 14.746944 , 18.646755 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(5, 5, 2), dtype=float32, numpy=
 array([[[-0.55909735, -0.5347214 ],
       

In [199]:
# 2. Find the shape, rank and size of the tensors you created in 1
(vector.shape, vector.ndim, tf.size(vector)), (scalar.shape, scalar.ndim, tf.size(scalar)), (matrix.shape, matrix.ndim, tf.size(matrix)), (tensor.shape, tensor.ndim, tf.size(tensor))

((TensorShape([4]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=4>),
 (TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>),
 (TensorShape([5, 10]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=50>),
 (TensorShape([5, 5, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=50>))

In [ ]:
# 3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [201]:
a = tf.constant(tf.random.uniform(shape=[5, 300]))
b = tf.constant(tf.random.uniform(shape=[5, 300]))
a, b

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.95831835, 0.01680839, 0.3156035 , ..., 0.67105925, 0.76730955,
         0.20125735],
        [0.09921694, 0.02475083, 0.47242153, ..., 0.9631474 , 0.34333456,
         0.8129494 ],
        [0.08817983, 0.9311962 , 0.2293179 , ..., 0.41450226, 0.008304  ,
         0.02438807],
        [0.54814565, 0.37019622, 0.5272658 , ..., 0.8656951 , 0.19644582,
         0.5959221 ],
        [0.8964087 , 0.15288067, 0.3360591 , ..., 0.5725572 , 0.4094149 ,
         0.40059018]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.43555546, 0.52486527, 0.49674678, ..., 0.00552487, 0.3156761 ,
         0.22303641],
        [0.93881905, 0.02025807, 0.8929347 , ..., 0.47184265, 0.93879664,
         0.27382708],
        [0.8537835 , 0.287457  , 0.57827055, ..., 0.22605908, 0.62864304,
         0.28893173],
        [0.83130777, 0.13316286, 0.4270022 , ..., 0.96334374, 0.81353974,
         0.47423255],
        [0.20213

In [204]:
# 4. Multiply the two tensors you created in 3 using matrix multiplication.
tf.matmul(a, tf.transpose(b)), tf.matmul(tf.transpose(a), b)

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[73.45298 , 74.09732 , 74.09219 , 73.014366, 73.15687 ],
        [74.90097 , 75.270905, 77.775635, 74.378746, 74.9059  ],
        [83.04033 , 79.46228 , 82.30002 , 80.63678 , 78.7219  ],
        [76.866684, 76.41698 , 79.003265, 77.38613 , 77.40253 ],
        [76.20903 , 74.70784 , 79.07423 , 75.5235  , 73.947845]],
       dtype=float32)>,
 <tf.Tensor: shape=(300, 300), dtype=float32, numpy=
 array([[1.2227077 , 0.74635607, 1.7006097 , ..., 1.4339572 , 1.175743  ,
         0.89622366],
        [1.164247  , 0.35069013, 0.87213147, ..., 0.7211163 , 0.9626345 ,
         0.5182214 ],
        [1.2830186 , 0.3649675 , 1.2553747 , ..., 1.0970403 , 1.2207333 ,
         0.6547262 ],
        ...,
        [2.385793  , 0.6975059 , 2.3462267 , ..., 1.9184322 , 2.258906  ,
         1.1799669 ],
        [0.9096889 , 0.5035559 , 1.1650587 , ..., 0.738209  , 0.8568732 ,
         0.5296512 ],
        [1.4480615 , 0.2723792 , 1.4747108 , ..., 1.336

In [211]:
# 5. Multiply the two tensors you created in 3 using dot product.
tf.tensordot(a, tf.transpose(b), axes = 1), tf.tensordot(tf.transpose(a), b, axes = 1), tf.tensordot(a, tf.transpose(b), axes = 0), tf.tensordot(tf.transpose(a), b, axes = 0)

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[73.45298 , 74.09732 , 74.09219 , 73.014366, 73.15687 ],
        [74.90097 , 75.270905, 77.775635, 74.378746, 74.9059  ],
        [83.04033 , 79.46228 , 82.30002 , 80.63678 , 78.7219  ],
        [76.866684, 76.41698 , 79.003265, 77.38613 , 77.40253 ],
        [76.20903 , 74.70784 , 79.07423 , 75.5235  , 73.947845]],
       dtype=float32)>,
 <tf.Tensor: shape=(300, 300), dtype=float32, numpy=
 array([[1.2227077 , 0.74635607, 1.7006097 , ..., 1.4339572 , 1.175743  ,
         0.89622366],
        [1.164247  , 0.35069013, 0.87213147, ..., 0.7211163 , 0.9626345 ,
         0.5182214 ],
        [1.2830186 , 0.3649675 , 1.2553747 , ..., 1.0970403 , 1.2207333 ,
         0.6547262 ],
        ...,
        [2.385793  , 0.6975059 , 2.3462267 , ..., 1.9184322 , 2.258906  ,
         1.1799669 ],
        [0.9096889 , 0.5035559 , 1.1650587 , ..., 0.738209  , 0.8568732 ,
         0.5296512 ],
        [1.4480615 , 0.2723792 , 1.4747108 , ..., 1.336

In [212]:
# 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor = tf.constant(tf.random.uniform(shape=[224, 224, 3]))
tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.14241445, 0.40161622, 0.33360183],
        [0.6816542 , 0.69087017, 0.22069418],
        [0.61336195, 0.9588975 , 0.3314948 ],
        ...,
        [0.21534526, 0.8758553 , 0.90849984],
        [0.913136  , 0.3300879 , 0.21957576],
        [0.294909  , 0.51060224, 0.41247094]],

       [[0.24516141, 0.0526433 , 0.8009639 ],
        [0.39559937, 0.91123044, 0.66148484],
        [0.62018025, 0.13185847, 0.2584139 ],
        ...,
        [0.69155025, 0.35061288, 0.7918345 ],
        [0.71887565, 0.13187587, 0.6776898 ],
        [0.91522217, 0.72013485, 0.5736792 ]],

       [[0.32997262, 0.01919758, 0.7673421 ],
        [0.37867343, 0.09564745, 0.07906318],
        [0.7100911 , 0.934427  , 0.5622425 ],
        ...,
        [0.8063401 , 0.53997624, 0.9590297 ],
        [0.7728716 , 0.5758432 , 0.53311133],
        [0.00398016, 0.15231979, 0.6468185 ]],

       ...,

       [[0.3400538 , 0.40921474, 0.04457414],
        [0.86

In [218]:
# 7. Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_max(tensor), tf.reduce_min(tensor)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9999963>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.172325e-06>)

In [219]:
# 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

tensor = tf.constant(tf.random.uniform(shape=[1, 224, 224, 3]))
tensor.shape, tf.squeeze(tensor).shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

In [229]:
# 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
tensor = tf.constant([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor.shape, tf.math.argmax(tensor)

(TensorShape([10]), <tf.Tensor: shape=(), dtype=int64, numpy=9>)

In [230]:
# 10. One-hot encode the tensor you created in 9.
tf.one_hot(tensor, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>